name: Coverity Scan

# We only want to run this on demand at the moment
on: workflow_dispatch

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: Set up build JDK
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        distribution: 'temurin'
        java-version: '25'
        check-latest: true
        cache: 'maven'
    - uses: vapier/coverity-scan-action@2068473c7bdf8c2fb984a6a40ae76ee7facd7a85 # v1.8.0
      with:
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
        build_language: 'java'
        command: 'mvn -DskipTests=true compile'
