name: Build Javadocs and Deploy to Github Pages
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
  release:
    types: [published]      
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up build JDK
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          distribution: 'temurin'
          java-version: '25'
          check-latest: true
      - name: Build Javadoc
        run: ./mvnw -B -V -e javadoc:javadoc
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          folder: target/reports/apidocs
          target-folder: ${{github.ref_name}}
